### ISSUE TITLE
请教使用

### ISSUE THREAD

**Issue by JTanCoder** [silent-field/task-orchestration#1]
您好，感谢分享，这个具体怎么结合XXL_JOB来使用呢，
最近在用到XXL_JOB也有DAG调度方面的需求,
有没有一些测试用例呢
感谢！

**Comment by silent-field** [comment]
你好，使用方式可以参考以下步骤
1.  使用xxl-job的任务id画出任务依赖形成DAG，并保存到DB中，例子参考DefaultTaskDAGStoreTest.testSave方法，该例子构建了一个任务依赖DAG图如下
 		3		4
 		 \	   /
 			2		5
		  /	  \          /
 		6		1
2. 根目录下有个sample工程，根据步骤1创建了6个xxl-job handler，对应注解@XxlJob("dag-test-1")~@XxlJob("dag-test-6")，在这6个handler方法上加上任务依赖注解@XxlJobTaskOrchestration。使用这个注解会有切面XxlJobTaskOrchestrationAspect进行对应的处理。
例如执行任务id=2会判定不能执行，执行过任务3跟4后可以触发一次任务2的执行。
详细代码可以参考sample工程，注意如果使用spring boot需要加上包扫描@ComponentScan(value = {"com.slient.task.orchestration"})，并且启动参数需要加上db配置，如：-Ddag_jdbc_username=root -Ddag_jdbc_password=123456 -Ddag_jdbc_url=jdbc:mysql://127.0.0.1:3306/dag_test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=GMT%2B8
